run_number: 5

click_data: weekly_normed
trans_data: weekly_normed

click_params:
    cat_id: True
    level_0: False
    level_1: False
    level_2: False
    filter_count: 50
    normed: False

trans_params:
    counts: True
    sums: True
    sign: combined
    filter_count: 50
    normed: False
    convert_currency: False

click_time_features: ['hour']
trans_time_features: ['hour']

train_params:
    sample_size: 70
    validation: False
    resample_freq: 1000
    random_state: 42
    thread_count: 20
    verbose: 500

catboost_params:
    iterations: 15000
    learning_rate: 0.03
    depth: 8
    l2_leaf_reg: 0.77
    random_seed: 42
    use_best_model: False
